//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace AzureServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public int Status { get; set; }
        public int Category { get; set; }
        public int RepeatType { get; set; }
        public int Period { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public int EndTime { get; set; }
        public System.DateTime EndDate { get; set; }
        public int UserID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public bool IsBreakable { get; set; }

        [IgnoreDataMember]
        public virtual Category Category1 { get; set; }
        [IgnoreDataMember]
        public virtual Project Project { get; set; }
        [IgnoreDataMember]
        public virtual RepeatType RepeatType1 { get; set; }
        [IgnoreDataMember]
        public virtual User User { get; set; }
        [IgnoreDataMember]
        public virtual Priority Priority1 { get; set; }
    }
}
